### ISSUE TITLE
Freature request - send mail.

### ISSUE THREAD

**Issue by mik-laj** [zurb/foundation-emails-template#1]
Hi.
I think it advisable to add the ability to send messages.
Similar project: https://github.com/sparkbox/email-lab 
It has such features. This facilitates testing on mobile devices and show your work boss, when he is not a technical person.

Thanks in advance!

-------
Polish message: 
Cześć
Ja uważam, że przydatne mogło by być dodanie możliwość wysłania wiadomości z templatką.
Podobny projekt: https://github.com/sparkbox/email-lab 
On posiada tą funkcje. Jest to szczególne przydatne przy testowaniu na urządzeniach mobilnych i przy pokazywaniu swoich wyników pracy szefowi, kiedy on nie jest osobą techniczną.

Dzięki z góry

**Comment by gakimball** [comment]
This has been a common suggestion so far, so we'll definitely be taking it into consideration.

Tomorrow we're going to be open-sourcing the Foundation for Emails repo, and we'll be closing this issue tracker in favor of that one.
