### ISSUE TITLE
npm ERR! code E404

### ISSUE THREAD

**Issue by joggienl** [zurb/foundation-emails-template#6]
Hello,

Cloning the master from this repo gives me an NPM error while trying to run npm install.

```bash
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "path:\\to\\nodejs\\node.exe" "path:\\to\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.1
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/foundation-emails
npm ERR! 404
npm ERR! 404  'foundation-emails' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'foundation-emails-template'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Obviously it states that it can't find the foundation-emails package in the npm registry. I noticed this reference in the package.json:

```json
  "dependencies": {
    "foundation-emails": "2.0.0-rc.1"
  }
```

What does this package do and where can it be found? Thanks in advance!

**Comment by gakimball** [comment]
Foundation for Emails 2 is being open-sourced on Thursday (shhh!)—this template was updated today to prepare for that. Until then, it's not quite fully operational, because we haven't published the `foundation-emails` package to npm yet. So stay tuned! :)

**Comment by joggienl** [comment]
Thanks, curious to see it then!
